[build]
builder = "nixpacks"

[build.env]
PYTHON_VERSION = "3.10.12"

[phases.setup]
nixPkgs = ["python310", "ffmpeg"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.deploy]
cmds = ["python bot.py"]
